# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "j7k6/kali-linux"
  #config.vm.box_version = "2019.2.0"

  config.vm.box = "kalilinux/rolling"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../handshakes", "/handshakes"

  config.vm.boot_timeout = 600

  # Enable provisioning with a shell script,
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
  export DEBIAN_FRONTEND=noninteractive
  apt-get -y --allow-unauthenticated update
	apt-get -y install curl
  wget   http://old-releases.ubuntu.com/ubuntu/pool/universe/h/hcxtools/hcxtools_6.0.2-1_amd64.deb
  apt-get -y install ./hcxtools_6.0.2-1_amd64.deb
	curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
	apt-get -y install nodejs
  cd /handshakes/pwnagetty
  npm install
  node pwnagetty.js
  SHELL
end
